CRITICAL - 2022-08-09 04:11:15 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(21): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:11:48 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(21): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:11:50 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(21): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:12:05 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(21): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:17:44 --> Class 'App\Libraries\Oauth' not found
in APPPATH\Controllers\User.php on line 15.
 1 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:17:45 --> Class 'App\Libraries\Oauth' not found
in APPPATH\Controllers\User.php on line 15.
 1 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:18:09 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:18:11 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:18:40 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:21:41 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:23:22 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:23:25 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-09 04:23:26 --> invalid data source name
in VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php on line 67.
 1 VENDORPATH\bshaffer\oauth2-server-php\src\OAuth2\Storage\Pdo.php(67): PDO->__construct('ROOTPATH\\public', 'root', 'ROOTPATH\\public', [])
 2 APPPATH\Libraries\Oauth.php(24): OAuth2\Storage\Pdo->__construct([...])
 3 APPPATH\Libraries\Oauth.php(12): App\Libraries\Oauth->init()
 4 APPPATH\Controllers\User.php(15): App\Libraries\Oauth->__construct()
 5 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\User->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
